import React, { useState } from 'react';
import { getTotalRentGenerated } from '../api/api';

const RentDetails: React.FC = () => {
  const [bookName, setBookName] = useState('');
  const [rent, setRent] = useState<number | null>(null);
  const [error, setError] = useState<string | null>(null);

  const fetchRentDetails = async () => {
    try {
      setError(null); // Reset error before fetching data
      const response = await getTotalRentGenerated(bookName);

      // Assuming API returns totalRent as null or an empty object if book not found
      if (response.data.totalRent !== null) {
        setRent(response.data.totalRent);
      } else {
        setError('Book not found or no rent generated.');
        setRent(null);  // Clear rent in case of error
      }
    } catch (error) {
      setError('Error fetching rent details. Please try again later.');
      setRent(null);  // Clear rent on error
    }
  };

  return (
    <div>
      <h2>Rent Generated by Book</h2>
      <input
        type="text"
        placeholder="Enter Book Name"
        value={bookName}
        onChange={(e) => setBookName(e.target.value)}
      />
      <button onClick={fetchRentDetails}>Fetch Rent</button>

      {error && <p style={{ color: 'red' }}>{error}</p>} {/* Display error message */}

      {rent !== null && <p>Total Rent: {rent}</p>} {/* Display rent if available */}
    </div>
  );
};

export default RentDetails;
